name: DiscordMCAPI
description: A plugin to integrate Discord with Minecraft servers.
authors: ["xSlay", "DiscordMCAPI"]
version: 1.0
main: com.discordconnection.plugin.Main
api-version: 1.20


commands:
  toggleplugin:
    description: Activa o desactiva funciones del plugin
    usage: /toggleplugin
    permission: discordmcapi.toggle
  registerapi:
    description: Registra este servidor en la API
    usage: /registerapi
